### ISSUE TITLE
__init_subclass_with_meta__() got multiple values for keyword argument '_meta'

### ISSUE THREAD

**Issue by DOsinga** [flavors/django-graphql-geojson#1]
Hi there,

Looks like a very useful project! However when I run the example code, I am getting the error of the subject:
"__init_subclass_with_meta__() got multiple values for keyword argument '_meta'"

I traced this to __init_subclass_with_meta__ of DjangoObjectType which at this point will have a _meta field in its properties, but it goes ahead and creates a _meta of its own and calls the super which will now receive two of them. Any thoughts on how to fix this? Seems like something changed, maybe.

Thanks,

Douwe

**Comment by mongkok** [comment]
Hi @DOsinga,

this library is based on a recently merged pull request [graphql-python/graphene-django/pull/379](https://github.com/graphql-python/graphene-django/pull/379).
Follow the steps to **update** graphene-django with the latest changes from master

```sh
pip install -U git+https://github.com/graphql-python/graphene-django.git@master
```

**Comment by ramaprashanth** [comment]
From graphene-django==2.0.1 && graphene==2.1  it is working !!

**Comment by mongkok** [comment]
Upgraded graphene-django requirement to v2.1rc0.
